### ISSUE TITLE
Investigate using snap to decrease stored theme sizes.

### ISSUE THREAD

**Issue by jacobsky** [jacobsky/egui-stylist#10]
[Snap](https://docs.rs/snap/1.0.5/snap/) may be a good format for the Egui-Theme to allow it to be compressible.

This should be a feature flag as it may not be necessary in all applications.

In addition to the necessary feature flags, the `EguiTheme` should store an extra field mentioning the version it was created with and whether or not it is compressed.

If the compression is not enabled for a compressed `EguiTheme` emit an error letting the parser know that it cannot decompress it without the feature flag, otherwise if compression is enabled it can optionally decompress if it is indicated to be compressed.

## Tasks
- [ ] Test to see space savings, no point in implementing it if there's no savings.
- [ ] Determine if the runtime data can be stored as compressed memory.
- [ ] Implement snap as feature flag
- [ ] Implement additional meta-data to the Ron file.
- [ ] Add all the compression information as an inner type.

**Comment by jacobsky** [comment]
While this could be useful, it doesn't have any immediate benefits. As #11 has a version tag, this can be easily implemented as an opt-in feature as a non-breaking change at a later time. Removing it from the 0.1.0 release milestone.

**Comment by jacobsky** [comment]
One side-note: It's not like the compression side can't just be relegated to end-users. The purpose behind this is to create reproducible themes in line with `egui`, not necesarily to hyper optimize this. In many ways, using snap may be a bit out of scope for this. The main benefit comes from lowering the size of the font-data, but if space is a concern, end users can just as easily compress the resulting themes and do the compression/decompression over the library.

**Comment by jacobsky** [comment]
This is out of scope, compressing the themes is not a in the cards at the moment.
